stages:
  - triggers

lint:
  stage: triggers
  trigger:
    include: .ci/lint.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

build_export_templates:
  stage: triggers
  trigger:
    include: .ci/build_export_templates.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
